### ISSUE TITLE
Issues with buildnumber-maven-plugin

### ISSUE THREAD

**Issue by andrebbc** [excelsior-oss/excelsior-jet-maven-plugin#49] opened 2017-01-10 08:13 UTC
I would like to use buildnumber-maven-plugin to append the buildnumber in the finalName. When I define the finalName like this:
``
<finalName>${project.artifactId}-${project.version}-${buildNumber}</finalName>
``

I need to explicitly set the mainJar property like this:
``
<mainJar>target/${project.build.finalName}.jar</mainJar>
``
And run `mvn buildnumber:create jet:build` in order for the jet plugin to find the jar and proceed with the build.

However during the jet packaging, the ${buildNumber} property is not populated anymore and the final package resolves to xxx-1.1-SNAPSHOT-${buildNumber}.zip

Similar maven issue with maven-jgit-buildnumber-plugin:
[https://github.com/simpligility/android-maven-plugin/issues/458](url)

**Comment by pjBooms** [comment] 2017-01-12 08:35
Fixed in 0.9.2 release.
You may also remove <mainJar>target/${project.build.finalName}.jar</mainJar> workaround.

Please confirm that the issue is fixed.

**Closed by pjBooms** 2017-01-12 08:35 UTC

**Comment by andrebbc** [comment] 2017-01-12 09:31
Tested in 0.9.2 release and verified that it is working. Thanks!
